version: '3.1'

services:

  redmine:
    build:
      context: .
      dockerfile: makethemdir
    restart: always
    depends_on:
      - db
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_PASSWORD: mysecretpass
      REDMINE_SECRET_KEY_BASE: supersecretkey

  db:
    image: postgres:11-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpass
      POSTGRES_DB: redmine
